### ISSUE TITLE
How to retrieve locally my WTS wallet?

### ISSUE THREAD

**Issue by victornoel** [zold-io/zold#788]
**Is your feature request related to a problem? Please describe.**

I would like to make a backup of my WTS wallet locally (mainly because I don't trust WTS completely for not loosing my money).

**Describe the solution you'd like**

Clear instructions on how to do that, and in particular how to run zold with the private key I retrieved from WTS.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by golyalpha** [comment]
@victornoel 
https://wts.zold.io/key to get the private key (you'll need the Keygap)

Then you'll need to generate the public key from the private key using `ssh-keygen -y -f .ssh/zold_key > .ssh/zold_key.pub`

Then, when using the zold CLI, there's a --private-key/--public-key flag, which you can use to specify what private/public key to use for the action.
Not sure if there's a way to change the default pubkey/privkey configuration (currently id_rsa) so that you don't have to specify it, the simplest way to do that might be to edit the code where the defaults are specified, and rebuild it.

**Comment by victornoel** [comment]
@golyalpha thank you for those informations, very useful.

@yegor256 what do you think about
- documenting this in the README
- add a way to change the keys being used by zold

**Comment by yegor256** [comment]
@victornoel maybe you can submit a PR for the README file of zold/wts.zold.io repo?

**Comment by victornoel** [comment]
@yegor256 one last question: what is the name of the configuration file, I don't see this information in the README

**Comment by yegor256** [comment]
@victornoel it's `~/.zold`

**Comment by victornoel** [comment]
@yegor256 btw I've made a PR as discussed: #792

**Comment by yegor256** [comment]
@victornoel merged, thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#788` is not assigned, can't get performer
