### ISSUE TITLE
Check wallet ballance without ledger

### ISSUE THREAD

**Issue by g4s8** [zold-io/zold#95]
How to validate that a wallet has required amount of Zold to send to another wallet? User can create two wallets then create and sign a transaction from wallet-1 to wallet-2 with X amount of Zold (without pushing) then send from wallet-2 to some other wallet X Zold and push it. To prevent it all nodes should know about each wallet in system, but there is no general ledger here.

**Comment by yegor256** [comment]
@g4s8 in order to make sure the a wallet has enough money you have to `pull` it and make sure the summary score you get after pulling is "big enough". In other words, it's up to you either to trust the wallet or not. In the future we will introduce a total score calculation: #96. The system will tell you how trustable is the wallet. Make sense?

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a84a658b-d428-431e-a01d-1a63941b2b3c, thread: pool-142-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#95, Action: `opened`

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed. If you have any further questions, please submit to zold-io/papers repo.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#95` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by g4s8** [comment]
@yegor256 thanks
